version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  maildev:
    image: maildev/maildev:2.1.0
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  app:
    build: ..
    container_name: mini-crm
    ports:
      - "5555:5555"
    depends_on:
      - mongo
      - maildev
    env_file: .env.local
    command: sh -c "npm run start:prod"

volumes:
  mongo_data:

